import array as arr
num=arr.array('i', [10,200,130,40,50]) 
print("The original array is:",num) 
print("Lenght of the array is:", len(num)) 
num.insert(2,55) 
print("Insert a new item at the specified index:", num) 
num.append(30) 
print("Append a new item to the end of the array:", num) 
print("Access the second item index of the array:", num.index(200)) 
num.reverse() 
print("Reverse of the array:", num) 
print("Concatenation of the array is:", num+num) 
print("Remove the item at the 3rd index:", num.pop(5)) 
print("Remove the item at the end of the array:", num.pop())
